{
 "title": "NodeInfo",
 "tags": [
  "nodes",
  "meshviewer"
 ],
 "time": { "from": "now-7d", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SHOW TAG VALUES FROM \"node\" WITH KEY = \"nodeid\""
   },
   { "name": "saveinterval", "label": "Interval yanic (in s)", "query": "60,360,600,3600" }
  ]
 },
 "panels": [
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "node",
     "select": [
      [
       { "params": [ "clients.total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"clients\") FROM (SELECT mean(\"clients.total\") as \"clients\" FROM \"node\" WHERE (\"nodeid\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"nodeid\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT min(\"uptime\") FROM (SELECT mean(\"time.up\") as \"uptime\" FROM \"node\" WHERE (\"nodeid\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval), \"nodeid\" fill(null)) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "time.up" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Missing Statistics Responses",
   "type": "graph",
   "description": "Percent of missing statistics responses. Lots of missing responses may indicate some kind of overload or bottleneck between this node and the statistics (\"respondd\") server.",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"missing_response\")/(sum(\"missing_response\")+sum(\"received_response\"))*100 as \"Missing Statistics Data\" FROM\n(SELECT 1-count(\"clients.total\") AS \"missing_response\", count(\"clients.total\") AS \"received_response\" FROM \"node\" WHERE (\"nodeid\" =~ /$node$/) AND $timeFilter GROUP BY time([[saveinterval]]s) fill(0))\nGROUP BY time($__interval*10) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bereich für Meshviewer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Clients\") AS \"Clients\",  sum(\"5 GHz\") AS \"5 GHz\" FROM (SELECT mean(\"clients.total\") AS \"Clients\", mean(\"clients.wifi5\") AS \"5 GHz\" FROM \"node\" WHERE (\"nodeid\" =~ /$node$/) AND $timeFilter GROUP BY \"nodeid\",time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.wifi5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5 GHz" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"down\") AS \"down\", sum(\"up\") AS \"up\", sum(\"mgmt_down\") AS \"mgmt_down\",  sum(\"mgmt_up\") AS \"mgmt_up\", sum(\"forward\") AS \"forward\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"traffic.rx.bytes\"), 1s) * 8 AS \"down\",   NON_NEGATIVE_DERIVATIVE(LAST(\"traffic.tx.bytes\"), 1s) * 8 AS \"up\", NON_NEGATIVE_DERIVATIVE(LAST(\"traffic.mgmt_rx.bytes\"), 1s) * 8 * count(\"traffic.mgmt_rx.bytes\") / count(\"traffic.mgmt_rx.bytes\") AS \"mgmt_down\",  NON_NEGATIVE_DERIVATIVE(LAST(\"traffic.mgmt_tx.bytes\"), 1s) * 8 AS \"mgmt_up\", NON_NEGATIVE_DERIVATIVE(LAST(\"traffic.forward.bytes\"), 1s) * 8 AS \"forward\" FROM \"node\" WHERE (\"nodeid\" =~ /^$node$/) AND $timeFilter GROUP BY \"nodeid\",time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "traffic.rx.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "down" ], "type": "alias" }
      ],
      [
       { "params": [ "traffic.tx.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*-8" ], "type": "math" },
       { "params": [ "up" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Neighbours (wie vorheriger Wert)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Total\") AS \"Total\",  sum(\"VPN\") AS \"VPN\" FROM (SELECT mean(\"neighbours.total\") AS \"Total\", mean(\"neighbours.vpn\") AS \"VPN\" FROM \"node\" WHERE \"nodeid\" =~ /$node$/ AND $timeFilter GROUP BY \"nodeid\",time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "neighbours.total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "neighbours.vpn" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "VPN" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Systemlast",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"Load\") AS \"Load\", mean(\"Mem\") AS \"Mem\" FROM (SELECT mean(\"load\") AS \"Load\", (1-(mean(memory.free)+mean(memory.buffers)+mean(memory.cached))/mean(memory.total) ) AS \"Mem\" FROM \"node\" WHERE (\"nodeid\" =~ /$node$/) AND $timeFilter GROUP BY \"nodeid\",time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Load" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "(memory.total-memory.free)/memory.total"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Mem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Airtime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT max(\"5 Ghz\") AS \"5 Ghz\", max(\"2.4 Ghz\") AS \"2.4 Ghz\" FROM (SELECT mean(\"airtime11a.chan_util\") AS \"5 Ghz\", mean(\"airtime11g.chan_util\") AS \"2.4 Ghz\" FROM \"node\" WHERE (\"nodeid\" =~ /$node$/) AND $timeFilter GROUP BY \"nodeid\",time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "airtime11a.chan_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "airtime11g.chan_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2.4 Ghz" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Zusätzlich",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "FFV Clients + Nodes (wie vorheriger Wert)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Clients\") AS \"Clients\", sum(\"Wifi\") AS \"Wifi\", sum(\"5Ghz\") AS \"5Ghz\", sum(\"Node\") AS \"Node\" FROM (SELECT mean(\"clients.total\") AS \"Clients\", mean(\"clients.wifi\") AS \"Wifi\", mean(\"clients.wifi5\") AS \"5Ghz\", count(\"load\") AS \"Node\" FROM \"node\" WHERE \"nodeid\" =~ /$node$/ AND $timeFilter GROUP BY \"nodeid\",time($interval) fill(null)) GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Clients" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.wifi" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Wifi" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.wifi5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "load" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Node" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/$node$/" }
     ]
    }
   ]
  }
 ]
}