{
 "title": "Link",
 "tags": [
  "nodes",
  "meshviewer"
 ],
 "time": { "from": "now-7d", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SHOW TAG VALUES FROM \"node\" WITH KEY = \"nodeid\""
   },
   { "name": "saveinterval", "label": "Interval yanic (in s)", "query": "60s,360s,600s,3600s" },
   {
    "name": "nodetolink",
    "query": "SHOW TAG VALUES FROM \"node\" WITH KEY = \"nodeid\""
   },
   {
    "name": "source_addr",
    "query": "SHOW TAG VALUES FROM \"link\" WITH KEY = \"source.addr\""
   },
   {
    "name": "target_addr",
    "query": "SHOW TAG VALUES FROM \"link\" WITH KEY = \"target.addr\""
   }
  ]
 },
 "panels": [
  {
   "title": "Knoten",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "node",
     "query": "SELECT \"nodeid\" AS \"NodeID\", last(\"clients.total\") AS \"Clients\" FROM \"node\" WHERE (\"nodeid\" =~ /^$node$/ OR \"nodeid\" =~ /^$nodetolink$/) AND $timeFilter GROUP BY \"hostname\" LIMIT 1",
     "select": [
      [
       { "params": [ "nodeid" ], "type": "field" },
       { "params": [ "NodeIDs" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Clients" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$node$/" },
      { "condition": "OR", "key": "nodeid", "operator": "=~", "value": "/^$nodetolink$/" }
     ]
    }
   ]
  },
  {
   "title": "Transmit quality between nodes [[node]] and [[nodetolink]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "link",
     "select": [
      [
       { "params": [ "tq" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "target.id", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "source.id", "operator": "=~", "value": "/^$nodetolink$/" },
      { "condition": "OR", "key": "source.id", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "target.id", "operator": "=~", "value": "/^$nodetolink$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "link",
     "select": [
      [
       { "params": [ "tq" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "target.id", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "source.id", "operator": "=~", "value": "/^$nodetolink$/" },
      { "condition": "OR", "key": "source.id", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "target.id", "operator": "=~", "value": "/^$nodetolink$/" }
     ]
    }
   ]
  },
  {
   "title": "Transmit quality between interfaces [[source_addr]] and [[target_addr]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[source_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "link",
     "select": [
      [
       { "params": [ "tq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source.addr", "operator": "=~", "value": "/^$source_addr$/" },
      { "condition": "AND", "key": "target.addr", "operator": "=~", "value": "/^$target_addr$/" }
     ]
    },
    {
     "alias": "[[target_addr]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "link",
     "select": [
      [
       { "params": [ "tq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source.addr", "operator": "=~", "value": "/^$target_addr$/" },
      { "condition": "AND", "key": "target.addr", "operator": "=~", "value": "/^$source_addr$/" }
     ]
    }
   ]
  },
  {
   "title": "Airtime on [[node]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       { "params": [ "airtime11g.chan_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Airtime 2,4GHz" ], "type": "alias" }
      ],
      [
       { "params": [ "airtime11a.chan_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Airtime 5GHz" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Airtime on [[nodetolink]]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       { "params": [ "airtime11g.chan_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Airtime 2,4GHz" ], "type": "alias" }
      ],
      [
       { "params": [ "airtime11a.chan_util" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Airtime 5GHz" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "nodeid", "operator": "=~", "value": "/^$nodetolink$/" }
     ]
    }
   ]
  }
 ]
}