{
 "title": "Globals",
 "tags": [
  "nodes",
  "network",
  "public"
 ],
 "time": { "from": "now-30d", "to": "now-1m" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Globals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "query": "SELECT mean(\"clients.wifi24\") AS \"Clients 2.4 Ghz\", mean(\"clients.wifi5\") AS \"Clients 5 Ghz\", mean(\"clients.total\") AS \"Clients Total\", mean(\"nodes\") AS \"Nodes\" FROM \"global\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.wifi24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients 2.4 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.wifi5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients 5 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients Total" ], "type": "alias" }
      ],
      [
       { "params": [ "nodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Nodes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autoupdater",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autoupdater",
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"model\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "query": "SELECT last(\"clients.wifi24\") as \"2.4 Ghz\",  last(\"clients.wifi5\") as \"5 Ghz\", last(\"clients.total\") - last(\"clients.wifi\") as \"other\"  FROM \"global\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.wifi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "clients.wifi24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "clients.wifi5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "firmware",
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "model",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Knoten-Laufzeit in Tagen",
   "type": "graph",
   "description": "Das Histogramm zeigt die Verteilung der Laufzeit aller Knoten in Tagen (bis max. 14 Tage).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Anzahl Knoten" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "autoupdater" ], "type": "tag" }
     ],
     "measurement": "node",
     "query": "SELECT last(\"time.up\") / 86400.0 FROM \"node\" WHERE time.up <= 1209600 AND $timeFilter GROUP BY \"nodeid\"",
     "select": [
      [
       { "params": [ "time.up" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "Frebst-Past-wdr3600" }
     ]
    }
   ]
  },
  {
   "title": "Anzahl neugestarteter Knoten",
   "type": "graph",
   "description": "Anzahl Knoten, die innerhalb der letzten 2 Stunden neu gestartet wurden.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT count(\"innerCount\") FROM (SELECT count(\"time.up\") as innerCount FROM \"node\" WHERE (\"time.up\" < 7200) AND $timeFilter GROUP BY \"nodeid\" fill(null)) GROUP BY time(7200s) fill(null)",
     "select": [
      [
       { "params": [ "time.up" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "time.up", "operator": "<", "value": "3600" }
     ]
    }
   ]
  }
 ]
}