{
 "title": "Domain",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domain",
    "query": "SHOW TAG VALUES FROM \"node\" WITH KEY = \"domain\""
   },
   { "name": "saveinterval", "label": "Interval yanic (in s)", "query": "360,60,180,600,3600" }
  ]
 },
 "panels": [
  {
   "title": "Nutzer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[saveinterval]]s" ], "type": "time" },
      { "params": [ "nodeid" ], "type": "tag" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Nutzer\") as \"Nutzer\" FROM (SELECT MEAN(\"clients.total\") AS \"Nutzer\" FROM \"autogen\".\"node\" WHERE (\"domain\" = '$domain') and  $timeFilter GROUP BY \"nodeid\", time([[saveinterval]]s)) GROUP BY time([[saveinterval]]s)",
     "select": [
      [
       { "params": [ "clients.total" ], "type": "field" },
       { "params": [ "Nutzer" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "$domain" }
     ]
    }
   ]
  },
  {
   "title": "Nutzer (akkumuliert)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "[[saveinterval]]s" ], "type": "time" },
      { "params": [ "nodeid" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT mean(\"clients.total\") FROM \"node\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "$domain" }
     ]
    }
   ]
  },
  {
   "title": "Datenverkehr",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[saveinterval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Download\") as \"Download\" FROM (SELECT non_negative_derivative(last(\"traffic.rx.bytes\"), 1s) AS \"Download\" FROM \"autogen\".\"node\" WHERE (\"domain\" = '$domain') and  $timeFilter GROUP BY \"nodeid\", time([[saveinterval]]s)) GROUP BY time([[saveinterval]]s)\n",
     "select": [
      [
       { "params": [ "traffic.rx.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Download" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "$domain" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[saveinterval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Upload\") as \"Upload\" FROM (SELECT non_negative_derivative(last(\"traffic.tx.bytes\"), 1s) AS \"Upload\" FROM \"autogen\".\"node\" WHERE (\"domain\" = '$domain') and  $timeFilter GROUP BY \"nodeid\", time([[saveinterval]]s)) GROUP BY time([[saveinterval]]s)\n",
     "select": [
      [
       { "params": [ "traffic.tx.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "$domain" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "[[saveinterval]]s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "query": "SELECT sum(\"Mesh\") as \"Mesh\" FROM (SELECT non_negative_derivative(last(\"traffic.forward.bytes\"), 1s) AS \"Mesh\" FROM \"autogen\".\"node\" WHERE (\"domain\" = '$domain') and  $timeFilter GROUP BY \"nodeid\", time([[saveinterval]]s)) GROUP BY time([[saveinterval]]s)\n",
     "select": [
      [
       { "params": [ "traffic.forward.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mesh" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "$domain" }
     ]
    }
   ]
  }
 ]
}