{
 "title": "Row",
 "panels": [
  {
   "title": "Nutzer des Freifunk-Knotens (Local Clients)",
   "type": "graph",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(freifunk.node.$node.*.clients.total), 'clients')"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(freifunk.node.$node.*.time.up)"
    }
   ]
  },
  {
   "title": "LoadAvg",
   "type": "singlestat",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(freifunk.node.$node.*.load)"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "singlestat",
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "target": "divideSeries(sumSeries(freifunk.node.$node.*.memory.free), sumSeries(freifunk.node.$node.*.memory.total))"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(freifunk.node.$node.*.traffic.rx.bytes), 8)), 'rx')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(freifunk.node.$node.*.traffic.tx.bytes), 8)), 'tx')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(freifunk.node.$node.*.traffic.mgmt_rx.bytes), 8)), 'mgmt_rx')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(freifunk.node.$node.*.traffic.mgmt_tx.bytes), 8)), 'mgmt_tx')"
    },
    {
     "target": "alias(sumSeries(scaleToSeconds(nonNegativeDerivative(freifunk.node.$node.*.traffic.forward.bytes), 8)), 'forward')"
    }
   ]
  },
  {
   "title": "Airtime 2.4GHz",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(freifunk.node.$node.*.airtime11g.chan_util)"
    }
   ]
  },
  {
   "title": "Airtime 5GHz",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(freifunk.node.$node.*.airtime11a.chan_util)"
    }
   ]
  }
 ]
}